modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/blay09/TrashSlot/issues"
displayURL="https://minecraft.curseforge.com/projects/trashslot"
authors="BlayTheNinth"
license="MIT"

[[mods]]
modId="trashslot"
version="${file.jarVersion}"
displayName="TrashSlot"
description='''
Adds a trash slot to the inventory screen that allows deletion of unwanted items.
'''
